Translating options composition
vuejs-br/br.vuejs.org pull request #102
Opened 2017-08-30 01:48 UTC by kimuraz

Translating options composition

2017-08-30 19:05 UTC, ErickPetru requested changes
Algumas considerações foram deixadas como revisão, para que sejam atendidas antes do _merge_.

2017-08-30 19:05 UTC, ErickPetru commented on src/v2/api/index.md
> +  <p class="tip">Use `$parent` e `$children` com moderação - eles servem, na maioria das vezes, como saída de emergência. Use, preferencialmente, props e eventos para comunicação pai-filho.</p>
Padronizamos sempre que possível traduzir **props** para **propriedades**.

2017-08-30 19:05 UTC, ErickPetru commented on src/v2/api/index.md
> +  A opção `mixins` aceita um vetor de objetos mixin. Esses objetos mixin podem conter options da instância assim com as instâncias de objetos normais, e ele serão combinados com as eventuais options
- Padronizamos colocar em _itálico_ os termos que permanecem sem tradução, como _mixin_.
- O termo _options_ deve ser traduzido para opções sempre que possível.
- O termo _hook_ vem sendo traduzido como **gatilho** em boa parte da API, por exemplo [aqui](https://br.vuejs.org/v2/api/#beforeUpdate).
- Não abreviar "p. ex.", mantemos literalmente "por exemplo" durante todo o guia para facilitar a leitura.

2017-08-30 19:05 UTC, ErickPetru commented on src/v2/api/index.md
> +  A opção `inject` deve ser tanto um vetor de strings ou um objeto onde as chaves referenciam os nomes de bind local, e os valores sendo as chaves (string ou Symbol) para buscar nas inserções disponí
Toda vez que _string_ ou _strings_ se referir ao tipo de dados, grafamos em maiúsculas durante a tradução.

2017-08-30 19:05 UTC, ErickPetru commented on src/v2/api/index.md
> +  Isso é parecido com `mixins`, a diferença é que as options do componente tem maior prioridade sobre a fonte do componente que ele está extendendo.
A palavra _extend_ é traduzida como **estender** (com **s**) em português. Não existe sua grafia com **x**.

2017-08-30 19:05 UTC, ErickPetru commented on src/v2/api/index.md
> +  Esse par de options é usado para possibilitar que um componente pai sirva de injetor de dependência para todos os filhos, independente de quão funda é a hierarquia do componente, desde que eles sej
Além da palavra _feature_ estar grafada incorretamente na frase, não mantemos ela em inglês, já que a tradução **recurso** atendem bem.

2017-08-30 19:05 UTC, ErickPetru commented on src/v2/api/index.md
> +  Usando um valor injetado como default para uma prop:
O termo _default_ poderia estar traduzido para **padrão** e _prop_ para **propriedade**.

2017-09-04 21:15 UTC, kimuraz commented
Conserto hoje mais tarde, desculpe pela demora!

2017-09-05 01:17 UTC, kimuraz commented on src/v2/api/index.md
> +  <p class="tip">Use `$parent` e `$children` com moderação - eles servem, na maioria das vezes, como saída de emergência. Use, preferencialmente, props e eventos para comunicação pai-filho.</p>
Feito

2017-09-05 01:17 UTC, kimuraz commented on src/v2/api/index.md
> +  A opção `mixins` aceita um vetor de objetos mixin. Esses objetos mixin podem conter options da instância assim com as instâncias de objetos normais, e ele serão combinados com as eventuais options
Feito

2017-09-05 01:17 UTC, kimuraz commented on src/v2/api/index.md
> +  Isso é parecido com `mixins`, a diferença é que as options do componente tem maior prioridade sobre a fonte do componente que ele está extendendo.
Feito

2017-09-05 01:17 UTC, kimuraz commented on src/v2/api/index.md
> +  Esse par de options é usado para possibilitar que um componente pai sirva de injetor de dependência para todos os filhos, independente de quão funda é a hierarquia do componente, desde que eles sej
Feito

2017-09-05 01:17 UTC, kimuraz commented on src/v2/api/index.md
> +  A opção `inject` deve ser tanto um vetor de strings ou um objeto onde as chaves referenciam os nomes de bind local, e os valores sendo as chaves (string ou Symbol) para buscar nas inserções disponí
Feito

2017-09-05 01:17 UTC, kimuraz commented on src/v2/api/index.md
> +  Usando um valor injetado como default para uma prop:
Feito

2017-09-05 12:19 UTC, merged