Remoção de parágrafos duplicados
vuejs-br/br.vuejs.org pull request #175
Opened 2018-05-10 08:59 UTC by robertoentringer

Remoção de parágrafos em inglês com tradução.

2018-05-10 19:44 UTC, ErickPetru requested changes
Alguns trechos de tradução após os trechos em inglês removidos não estão muito claros ou contêm alguns erros. Favor revisar o que foi marcado.

2018-05-10 19:44 UTC, ErickPetru commented on src/v2/style-guide/index.md
>  O problema é também existem muitos casos simples em que esses padrões podem oferecer conveniência. Cuidado: não se deixe seduzir pela simplicidade de negociação (poder entender o fluxo do seu estado)
A segunda frase do parágrafo não está entregando exatamente o mesmo significado da versão em inglês, sobre trocar uma característica do código por outra.

2018-05-10 19:44 UTC, ErickPetru commented on src/v2/style-guide/index.md
>  **Props e eventos devem ser usados preferencialmente para a comunicação do componente pai-filho, em vez de `this.$Parent`.**
O código `this.$parent` está grafado incorretamente e falta o final da frase na tradução (propriedades de mutação).

2018-05-10 19:44 UTC, ErickPetru commented on src/v2/style-guide/index.md
>  ** [Vuex](https://github.com/vuejs/vuex) deve ser preferido para o gerenciamento de estado global, em vez de `this.$root` ou um o uso de event bus.**
O final da frase não está muito claro e poderia ser traduzido de forma mais conveniente.

2018-05-15 07:39 UTC, robertoentringer commented
Olá Erick, obrigado pelo feedback. Vou dar uma olhada nisso assim que puder. Abraços.

2018-12-03 19:36 UTC, ErickPetru commented
As revisões solicitadas não foram realizadas. Mas, ainda que tivessem sido, este arquivo ainda apresenta diversos problemas de tradução, frases de difícil compreensão, frases que tiveram o significado perdido após a tradução, termos traduzido fora do padrão do restante do projeto, etc. Tais problemas deverão ser resolvidos em outro _pull request_ mais completo.

2018-12-03 19:36 UTC, closed without merging